import { createFileRoute } from "@tanstack/react-router";
import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — Grow" },
      {
        name: "description",
        content:
          "How Grow collects, uses, stores and shares personal data across our talent operating system.",
      },
      { property: "og:title", content: "Privacy Policy — Grow" },
      {
        property: "og:description",
        content: "Grow's commitments around personal data, candidate data and AI processing.",
      },
    ],
  }),
  component: PrivacyPage,
});

const sections = [
  {
    title: "1. Data we collect",
    body: "We collect data you provide directly (account info, candidate records, scorecards), data generated by your use of Grow (interview transcripts, sourcing activity, pipeline events) and limited technical data (IP, device, browser) needed to operate the service securely.",
  },
  {
    title: "2. How we use data",
    body: "Customer data is used to deliver the Grow product to your team — surfacing candidates, drafting outreach, generating scorecards, and producing analytics. We do not sell personal data and we do not train shared foundation models on customer content.",
  },
  {
    title: "3. AI processing",
    body: "Generative features run on dedicated tenant-scoped inference. Prompts and outputs are retained only for the duration needed to deliver the response and to debug failures, and are never used to train models that serve other customers.",
  },
  {
    title: "4. Sharing & subprocessors",
    body: "We use a limited set of vetted subprocessors (cloud hosting, observability, email delivery, model providers under zero-retention agreements). The current list is available on request and updated at least 30 days before any material change.",
  },
  {
    title: "5. Your rights",
    body: "Candidates and employees can request access, correction, export or deletion of their personal data at any time by emailing privacy@grow.example. We respond within 30 days and honor regional rights under GDPR, UK GDPR, CCPA/CPRA and equivalents.",
  },
  {
    title: "6. Retention",
    body: "Customer data is retained for the life of your subscription plus 30 days, after which it is permanently deleted from primary systems and within 90 days from backups. Customers can configure shorter retention windows from inside the product.",
  },
  {
    title: "7. Contact",
    body: "Questions, requests or complaints — privacy@grow.example. Our EU representative is reachable via the same address.",
  },
];

function PrivacyPage() {
  return (
    <div className="relative min-h-screen overflow-hidden bg-background">
      <Navbar />
      <main className="mx-auto max-w-3xl px-6 pb-32 pt-32">
        <div className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Legal</div>
        <h1 className="mt-4 text-balance text-5xl font-semibold tracking-tight text-foreground sm:text-6xl">
          Privacy Policy
        </h1>
        <p className="mt-4 text-sm text-muted-foreground">Last updated April 1, 2026</p>
        <p className="mt-8 text-lg text-muted-foreground">
          Grow is built around the people inside your hiring funnel. We treat their data — and yours
          — with the seriousness that requires.
        </p>

        <div className="mt-16 space-y-10">
          {sections.map((s) => (
            <section key={s.title}>
              <h2 className="text-xl font-semibold text-foreground">{s.title}</h2>
              <p className="mt-3 text-muted-foreground">{s.body}</p>
            </section>
          ))}
        </div>
      </main>
      <Footer />
    </div>
  );
}
