import type { CSSProperties } from 'react'

export const brand = {
  main: {
    backgroundColor: '#ffffff',
    fontFamily: '"Geist Sans", Inter, system-ui, sans-serif',
    margin: 0,
    padding: '40px 0',
  } as CSSProperties,
  container: {
    maxWidth: '560px',
    margin: '0 auto',
    padding: '32px 28px',
    borderRadius: '16px',
    border: '1px solid #ececec',
    backgroundColor: '#ffffff',
  } as CSSProperties,
  brandMark: {
    fontSize: '14px',
    fontWeight: 600,
    letterSpacing: '0.04em',
    color: '#7c3aed',
    textTransform: 'uppercase' as const,
    margin: '0 0 24px',
  } as CSSProperties,
  h1: {
    fontSize: '24px',
    fontWeight: 600,
    color: '#0a0a0f',
    margin: '0 0 16px',
    letterSpacing: '-0.01em',
  } as CSSProperties,
  text: {
    fontSize: '15px',
    lineHeight: 1.6,
    color: '#3f3f46',
    margin: '0 0 20px',
  } as CSSProperties,
  button: {
    backgroundColor: '#7c3aed',
    color: '#ffffff',
    fontSize: '14px',
    fontWeight: 600,
    borderRadius: '999px',
    padding: '12px 24px',
    textDecoration: 'none',
    display: 'inline-block',
  } as CSSProperties,
  link: {
    color: '#7c3aed',
    textDecoration: 'underline',
  } as CSSProperties,
  code: {
    fontFamily: '"Geist Mono", ui-monospace, SFMono-Regular, monospace',
    fontSize: '28px',
    fontWeight: 600,
    letterSpacing: '0.18em',
    color: '#0a0a0f',
    backgroundColor: '#faf9ff',
    border: '1px solid #ece7fb',
    borderRadius: '12px',
    padding: '16px 20px',
    textAlign: 'center' as const,
    margin: '0 0 28px',
  } as CSSProperties,
  footer: {
    fontSize: '12px',
    color: '#8a8a93',
    margin: '32px 0 0',
    lineHeight: 1.6,
  } as CSSProperties,
}