/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewCopilotRouteImport } from './routes/interview-copilot'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewIndexRouteImport } from './routes/interview.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as InterviewRubricsRouteImport } from './routes/interview.rubrics'
import { Route as InterviewNewRouteImport } from './routes/interview.new'
import { Route as InterviewIdRouteImport } from './routes/interview.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as ShareScorecardTokenRouteImport } from './routes/share.scorecard.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicRecallWebhookRouteImport } from './routes/api/public/recall-webhook'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicScorecardTokenRouteImport } from './routes/api/public/scorecard.$token'
import { Route as ApiPublicHooksGenerateBlogPostRouteImport } from './routes/api/public/hooks/generate-blog-post'
import { Route as ApiPublicHooksAutoPublishBlogPostRouteImport } from './routes/api/public/hooks/auto-publish-blog-post'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewCopilotRoute = InterviewCopilotRouteImport.update({
  id: '/interview-copilot',
  path: '/interview-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIndexRoute = InterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRubricsRoute = InterviewRubricsRouteImport.update({
  id: '/interview/rubrics',
  path: '/interview/rubrics',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewNewRoute = InterviewNewRouteImport.update({
  id: '/interview/new',
  path: '/interview/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewIdRoute = InterviewIdRouteImport.update({
  id: '/interview/$id',
  path: '/interview/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/admin/contacts',
  path: '/admin/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareScorecardTokenRoute = ShareScorecardTokenRouteImport.update({
  id: '/share/scorecard/$token',
  path: '/share/scorecard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecallWebhookRoute = ApiPublicRecallWebhookRouteImport.update({
  id: '/api/public/recall-webhook',
  path: '/api/public/recall-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScorecardTokenRoute = ApiPublicScorecardTokenRouteImport.update({
  id: '/api/public/scorecard/$token',
  path: '/api/public/scorecard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateBlogPostRoute =
  ApiPublicHooksGenerateBlogPostRouteImport.update({
    id: '/api/public/hooks/generate-blog-post',
    path: '/api/public/hooks/generate-blog-post',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoPublishBlogPostRoute =
  ApiPublicHooksAutoPublishBlogPostRouteImport.update({
    id: '/api/public/hooks/auto-publish-blog-post',
    path: '/api/public/hooks/auto-publish-blog-post',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview-copilot': typeof InterviewCopilotRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/interview/$id': typeof InterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/interview/rubrics': typeof InterviewRubricsRoute
  '/blog/': typeof BlogIndexRoute
  '/interview/': typeof InterviewIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/recall-webhook': typeof ApiPublicRecallWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/share/scorecard/$token': typeof ShareScorecardTokenRoute
  '/api/public/hooks/auto-publish-blog-post': typeof ApiPublicHooksAutoPublishBlogPostRoute
  '/api/public/hooks/generate-blog-post': typeof ApiPublicHooksGenerateBlogPostRoute
  '/api/public/scorecard/$token': typeof ApiPublicScorecardTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview-copilot': typeof InterviewCopilotRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/interview/$id': typeof InterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/interview/rubrics': typeof InterviewRubricsRoute
  '/blog': typeof BlogIndexRoute
  '/interview': typeof InterviewIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/recall-webhook': typeof ApiPublicRecallWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/share/scorecard/$token': typeof ShareScorecardTokenRoute
  '/api/public/hooks/auto-publish-blog-post': typeof ApiPublicHooksAutoPublishBlogPostRoute
  '/api/public/hooks/generate-blog-post': typeof ApiPublicHooksGenerateBlogPostRoute
  '/api/public/scorecard/$token': typeof ApiPublicScorecardTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/interview-copilot': typeof InterviewCopilotRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/interview/$id': typeof InterviewIdRoute
  '/interview/new': typeof InterviewNewRoute
  '/interview/rubrics': typeof InterviewRubricsRoute
  '/blog/': typeof BlogIndexRoute
  '/interview/': typeof InterviewIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/recall-webhook': typeof ApiPublicRecallWebhookRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/share/scorecard/$token': typeof ShareScorecardTokenRoute
  '/api/public/hooks/auto-publish-blog-post': typeof ApiPublicHooksAutoPublishBlogPostRoute
  '/api/public/hooks/generate-blog-post': typeof ApiPublicHooksGenerateBlogPostRoute
  '/api/public/scorecard/$token': typeof ApiPublicScorecardTokenRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/forgot-password'
    | '/interview-copilot'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/rss.xml'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin/blog'
    | '/admin/contacts'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/interview/$id'
    | '/interview/new'
    | '/interview/rubrics'
    | '/blog/'
    | '/interview/'
    | '/api/public/contact'
    | '/api/public/recall-webhook'
    | '/lovable/email/suppression'
    | '/share/scorecard/$token'
    | '/api/public/hooks/auto-publish-blog-post'
    | '/api/public/hooks/generate-blog-post'
    | '/api/public/scorecard/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/forgot-password'
    | '/interview-copilot'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/rss.xml'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin/blog'
    | '/admin/contacts'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/interview/$id'
    | '/interview/new'
    | '/interview/rubrics'
    | '/blog'
    | '/interview'
    | '/api/public/contact'
    | '/api/public/recall-webhook'
    | '/lovable/email/suppression'
    | '/share/scorecard/$token'
    | '/api/public/hooks/auto-publish-blog-post'
    | '/api/public/hooks/generate-blog-post'
    | '/api/public/scorecard/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/customers'
    | '/forgot-password'
    | '/interview-copilot'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/rss.xml'
    | '/security'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/admin/blog'
    | '/admin/contacts'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/interview/$id'
    | '/interview/new'
    | '/interview/rubrics'
    | '/blog/'
    | '/interview/'
    | '/api/public/contact'
    | '/api/public/recall-webhook'
    | '/lovable/email/suppression'
    | '/share/scorecard/$token'
    | '/api/public/hooks/auto-publish-blog-post'
    | '/api/public/hooks/generate-blog-post'
    | '/api/public/scorecard/$token'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InterviewCopilotRoute: typeof InterviewCopilotRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminContactsRoute: typeof AdminContactsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InterviewIdRoute: typeof InterviewIdRoute
  InterviewNewRoute: typeof InterviewNewRoute
  InterviewRubricsRoute: typeof InterviewRubricsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  InterviewIndexRoute: typeof InterviewIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicRecallWebhookRoute: typeof ApiPublicRecallWebhookRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ShareScorecardTokenRoute: typeof ShareScorecardTokenRoute
  ApiPublicHooksAutoPublishBlogPostRoute: typeof ApiPublicHooksAutoPublishBlogPostRoute
  ApiPublicHooksGenerateBlogPostRoute: typeof ApiPublicHooksGenerateBlogPostRoute
  ApiPublicScorecardTokenRoute: typeof ApiPublicScorecardTokenRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-copilot': {
      id: '/interview-copilot'
      path: '/interview-copilot'
      fullPath: '/interview-copilot'
      preLoaderRoute: typeof InterviewCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/': {
      id: '/interview/'
      path: '/interview'
      fullPath: '/interview/'
      preLoaderRoute: typeof InterviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/rubrics': {
      id: '/interview/rubrics'
      path: '/interview/rubrics'
      fullPath: '/interview/rubrics'
      preLoaderRoute: typeof InterviewRubricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/new': {
      id: '/interview/new'
      path: '/interview/new'
      fullPath: '/interview/new'
      preLoaderRoute: typeof InterviewNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$id': {
      id: '/interview/$id'
      path: '/interview/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof InterviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/admin/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/scorecard/$token': {
      id: '/share/scorecard/$token'
      path: '/share/scorecard/$token'
      fullPath: '/share/scorecard/$token'
      preLoaderRoute: typeof ShareScorecardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recall-webhook': {
      id: '/api/public/recall-webhook'
      path: '/api/public/recall-webhook'
      fullPath: '/api/public/recall-webhook'
      preLoaderRoute: typeof ApiPublicRecallWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scorecard/$token': {
      id: '/api/public/scorecard/$token'
      path: '/api/public/scorecard/$token'
      fullPath: '/api/public/scorecard/$token'
      preLoaderRoute: typeof ApiPublicScorecardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-blog-post': {
      id: '/api/public/hooks/generate-blog-post'
      path: '/api/public/hooks/generate-blog-post'
      fullPath: '/api/public/hooks/generate-blog-post'
      preLoaderRoute: typeof ApiPublicHooksGenerateBlogPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-publish-blog-post': {
      id: '/api/public/hooks/auto-publish-blog-post'
      path: '/api/public/hooks/auto-publish-blog-post'
      fullPath: '/api/public/hooks/auto-publish-blog-post'
      preLoaderRoute: typeof ApiPublicHooksAutoPublishBlogPostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InterviewCopilotRoute: InterviewCopilotRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminContactsRoute: AdminContactsRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InterviewIdRoute: InterviewIdRoute,
  InterviewNewRoute: InterviewNewRoute,
  InterviewRubricsRoute: InterviewRubricsRoute,
  BlogIndexRoute: BlogIndexRoute,
  InterviewIndexRoute: InterviewIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicRecallWebhookRoute: ApiPublicRecallWebhookRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ShareScorecardTokenRoute: ShareScorecardTokenRoute,
  ApiPublicHooksAutoPublishBlogPostRoute:
    ApiPublicHooksAutoPublishBlogPostRoute,
  ApiPublicHooksGenerateBlogPostRoute: ApiPublicHooksGenerateBlogPostRoute,
  ApiPublicScorecardTokenRoute: ApiPublicScorecardTokenRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
